apiVersion: v1
kind: Service
metadata:
  name: emitter-http
spec:
  selector:
    app: broker
  ports:
    - port: 80
      targetPort: 8080
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: emitter-mqtt
  namespace: openfaas
spec:
  type: NodePort
  selector:
    app: broker
  ports:
    - port: 443
      targetPort: 443
      nodePort: 32323
      name: https
